[FE] TEAM-01 1주차 PR
codesquad-members-2023/second-hand pull request #18
Opened 2023-06-09 02:45 UTC by poco111

안녕하세요 빰빰 🖐️, 1주차 리뷰 pr입니다.

이번주에 진행 사항 및 고민에 대해서 공유드리겠습니다!

# 이번 주 작업 내용

개발 환경 초기 설정, 공통 컴포넌트 task 분리 및 공통 컴포넌트 작업 일부를 진행했습니다

# 기술 선택 기준

- pnpm을 사용하는 이유
    - 기존에 npm을 계속 사용했고, npm과 비슷하지만 속도가 빠른 pnpm을 선택했습니다.
    - 그외에도 아래 링크의 글을 읽으면서 여러가지 Ghost Dependency 문제를 해결하는 등 여러가지 이점이 있다고 판단하여 pnpm을 선택하였습니다.
    - https://hiddenest.dev/yarn-pnpm-3
- axios를 사용하지 않는 이유
    - 급하게 라이브러리를 도입하기 보다는 fetch 사용에 익숙해지고 싶은 마음에 axios를 도입하지 않기로 결정했습니다.
- Storybook
    - 컴포넌트 테스트를 위해 도입하였습니다.
    - 이를 적용해보니, 해당 컴포넌트를 실제 사용하기 이전에 props의 경우의 수에 따라서 테스트를 해볼 수 있다는게 장점으로 느껴졌습니다.
- Styled-components
    - theme를 전역에 지정하고 해당 theme를 사용할 수 있다는 점이 기존에 사용했던 css-module 보다는 편리했습니다.

# 고민

- 상태 관리
    - 전역으로 관리할 상태를 user정보, 메인목록에서 선택된 카테고리 필터 두 가지 정도를 생각하고 있고, 위의 두 가지 상태 외에는 해당 컴포넌트들에서 상태관리를 하려고 합니다.(차주에 구체화 할 예정)
- filter 적용시에 url에 선택된 filter를 명시적으로 추가하는 기능을 구현하여 새로고침을 해도 filter가 적용된 상태를 유지하는 방법을 고민중입니다.

# 다음주 예정 작업

- 상태 설계
    - 전체 프로젝트의 상태를 어떻게 관리할지에 대해서 설계할 예정입니다.
- 로그인 관련 공부 및 구현 작업 예정입니다.
- 상품 목록, 동네 설정 페이지 구현 작업 예정입니다.

2023-06-10 15:26 UTC, Jerome-Yoo requested changes
적극 코멘트가 몇개 있습니다. 확인을 부탁드립니다!

- 여러분이 시도했던 내용에 대해서는 저도 고민이 좀 필요한 지점이라 해당 내용을 정돈된 글로 표현해보고 있어요. 조만간 DM으로 내용을 전달해보겠습니다. 
- 질문이나 고민하는 내용은 곧 달아보겠습니다.

고생하셨어요! 👍 👍

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/styles/Color.ts
와 소름이 돋았습니다
디자이너가 있고, 적절하게 관리가 되어야 쓸 수 있는 방식을 스타일 관리 방식을 쓰시는 군요. 멋집니다.

[제안]
팔레트는 간단하게 가져와서 쓸 수 있다는 의미가 담겨있는 걸까요? 팔레트의 의미가 약간 애매하다는 생각이 드네요?

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/styles/Typography.ts
이것도 정말정말 좋은 관리 케이스라고 생각해요. 박수를 백번쳐주고 싶습니다 👏👏*50

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/styles/index.css
> +}
[제안]
폰트를 프로젝트의 내부 에셋으로 관리를 하다보면, 네트워크 페이로드가 커지는 문제를 갖게 되죠.
font의 경우 크기가 큰 스태틱 에셋인지라 다운로드-페인팅 의 과정이 오래 걸릴 수밖에 없어요.
lazy하게 다룰 수 있는 접근방식이 여러가지가 있습니다. 한번 시도해보시는게 어떨까요?

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/styles/GlobalStyle.ts
개인적으로는 스타일을 리셋하는 것을 보수적으로 접근하는 편입니다.
[웹 접근성의 측면](https://web.dev/learn/accessibility/)에서 스타일을 리셋하는 시도도 있어요. 
참고차원에서 링크를 전달드립니다.
https://github.com/mike-engel/a11y-css-reset

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/reportWebVitals.ts
이번이 마지막 프로젝트이지요? 그런만큼 학습 차원에서 링크를 남겨볼게요.
reportWebVitals를 실제로 작동시켜보면 [이런느낌](https://gusehd66.tistory.com/entry/React-CRA-%EB%94%94%ED%8F%B4%ED%8A%B8-%ED%8C%8C%EC%9D%BC%EC%9D%B8-reportWebVitals)인데요.

최근의 FE개발 영역에서 웹바이탈 측정이 도구차원에서 크게 발전하고 있다는 느낌을 받고 있어요. 곧 업무하시면서 만나게 될 도구라서 참고차원에서 남겨봅니다.
- [sentry](https://www.youtube.com/watch?v=rEhs0S3YaN0)
- [datadog rum](https://docs.datadoghq.com/real_user_monitoring/)

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/reportWebVitals.ts
이번 프로젝트에서는 다루지 못할 영역이긴 하지만, 웹 퍼포먼스를 이해하는 개발자는 시장에서 필요로 하고 있기 때문에
앞으로 학습할 때 관련 항목을 어떻게 다뤄볼 수 있을까? 도 고민해봤으면 좋겠어요.
방향을 잡기위해 어드바이스가 필요하시면 줌미팅을 주셔요~

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
[적극] 지금 이 두개의 파일은 빠져있지 않은가요? 크롬 네트워크창에서는 빨간 불이 들어왔겠군요.
삭제해야하는 라인이라고 생각해요.

2개의 파일은 SEO 차원에서는 대단히 큰 역할을 하는 파일입니다.
어떤 역할을 하시는지 seo apple-touch-icon, seo seo manifest.json 등의 키워드를 학습하시기를 강하게 권장드립니다.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/package.json
> +    "lint": "eslint . --ext .js",
[질문] 
음.. 이러면 린팅 커맨트는 타입스크립트에 대해서는 적용되지 않게 되지 않나요?

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/package.json
> +    "@storybook/testing-library": "^0.0.14-next.2",
[질문]
해당 라이브러리는 0.1.0이 최신 버전인 것 같아요. 아마도 자동설치되어서 챙기지 못한 부분인 것 같은데, 
불안정한 릴리즈 버전을 쓰고 있는게 아닌가 싶습니다?
<img width="1311" alt="image" src="https://github.com/codesquad-members-2023/second-hand/assets/88368753/c7b60fe0-a4c6-4ac4-9d2a-6392de7f6c81">

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/package.json
> +    "styled-components": "6.0.0-rc.3",
이것도 버전이 좀 불안정해서 찾아보니까 6버전은 Release Candidate 상태이더라구요.
보통 회사에서는 이런 경우에는 해당 버전 사용을 위해 우리가 떠안아야하는 리스크가 무엇인지 고민을 합니다.
아마도 npm install 하니까 요게 받아져서 쓴 것이긴 하겠지만 왜 이런 이상한 버전이 설치되었지? 하는 의문은 있었으면 좋겠어요🤝

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/assets/icons/index.ts
오잉 요것은 어떤 상황인지 제가 파악을 못하겠어요.
<img width="320" alt="image" src="https://github.com/codesquad-members-2023/second-hand/assets/88368753/95bf35b8-e0ef-4d1f-89d5-6aa3fff0dd4e">

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Button/ButtonStyle.ts
스타일을 아주 깔끔하게 다루시는군요. 저도 배워갑니다 👍

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Dropdown/Dropdown.tsx
> +      <Icon name={isOpen ? 'arrowUp' : 'arrowDown'}></Icon>
[제안]
(제안코멘트는 "바꿨으면 좋겠어요"는 아니고, 진짜로 제안수준이기 때문에, 협업하시는 분들의 커뮤니케이션을 필요로 한다 정도로 파악해주시면 좋겠습니다.)
아이콘의 사용에 대해 고민을 해보셨으면 좋겠습니다. 

각 아이콘을 추상화해놓으면, 지금처럼 사용할 때 참 편하다는 장점이 있는데요,
반대로 이렇게되면 문제가 되는 부분은, 다루는 아이콘의 갯수가 많아질 수록 관리가 잘 되지 않는다는 어려움을 가져요. **각 아이콘이 언제 어떻게 쓰이고 있지? 를 IDE 수준에서 레퍼런싱 기능으로 도움을 받지 못하기** 때문에 저희는 아이콘을 추상화 하지 않는다는 정책을 채택하고 있습니다.

개인적인 경험으로는 예전에 다른 프로젝트에서 개발자가 나가서 빨리 도움을 줘야 했던 시기가 있었는데요. 이 때 당시 개발자가 해당영역을 문서화해두지 않아서 아이콘 관리 체계를 엎었던 기억이 있어요. name을 써서 렌더링하는 것은 알겠는데, 그래서 어떤 이름을 써야하고, 막상 쓰고 나니 이름도 좀 이상하고 (ex. arrowUpBlack -> 얘는 화살표가 검은색 , questionBlack -> 얘는 물음표의 뒷배경이 검은색 등..) 이런 문제가 있었습니다.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Icon/Icon.tsx
> +export const Icon = ({ name = 'arrowDown', size = 16, color }: IconProps) => {
[적극]
name이 없으면 렌더링할 아이콘을 잘못쓰고 있다는 것인데, 
이 경우 기본값을 줘서 임의의 아이콘을 만들어주는게 아니라, 빈 영역을 만들고, 콘솔로 에러를 알려주든지 해야하는게 
아이콘 컴포넌트로서의 책임이 아닌가 싶어요.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Icon/Icon.tsx
> +}
[제안]
이 타입은 스타일과 관련된 프롭이기 때문에 컴포넌트 선언부에서 다뤄지는 것이 아니라 스타일쪽에서 다루고 export를 하는 것이 좀 더 자연스럽게 보여집니다.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Icon/IconStyle.ts
> +    color ? theme.colors[color] : theme.colors.neutralText};
[적극]
앞서 size는 기본값으로 16을 내려주었고, 그것이 합당하다고는 생각했는데요,
color는 스타일드 컴포넌트에서 undefined 검사를 해서 바꿔주고 있네요. 
사용하는 차원에서는 어떤것은 기본값이 드러나있고, 어떤 것은 드러나있지 않아서 얼라인이 맞지 않다는 느낌을 받습니다.

[제안]
개인적으로는 이 경우도 기본값을 할당해주는게 좋지 않은가 해요.
다만, theme으로 쓰는 지라 컴포넌트의 기본값으로서는 활용이 어려울 수 있겠군요. (이런 부분이 전역테마를 프로바이딩하는 것의 불편한점이라 생각해요.)

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/NavBar/NavBar.tsx
> +  onClick?: () => void;
[적극]
1. leftBtn, rightBtn에 무엇이 들어올지는 모르겠으나, onClick에 이벤트가 넘어오지 않는다는 선언은 잘못된 선언이라 생각되어요.
클릭이벤트가 넘어오는 형태로 변경되어야 할 것 같아요.

2. 버튼의 클릭이벤트가 optional이라는 것이 약간 납득이 되지 않는데요, 클릭 이벤트의 핸들러 함수가 없을 수 있다면, 클릭 이벤트를 네이티브 이벤트로서 사용해야하는 경우도 존재하는 걸까요? 적절한 변경이 있어야 할 것 같습니다.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Profile/Profile.tsx
> +}
앞서 제가 제안 코멘트로 달긴 했는데요, 이 타입은 해당 컴포넌트에서는 직접 사용되지 않네요.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Profile/ProfileStyle.ts
> +    left: 50%;
[제안]
카메라 아이콘이라는 className이 있을 때 wrapper에서 스타일을 직접 변경할 수 있도록 했네요.
그런데 이 부분은 카메라 아이콘을 감싸는 div가 가져야하는 책임이 아닌가 싶어요.

wrap은 단순하게는 감싼다는 의미인데, camera-icon의 스타일 변경을 담당하고 있기도 하네요. 이름이 모든 역할을 드러내지는 못하는 것 같아요. 분리여부를 떠나서 일단 네이밍에서는 적절하게 역할이 드러나지 않는 것 같습니다.

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Tab/Tab.tsx
> +  children: ReactElement | string;
[질문]
children에서 ReactElement를 쓰셨군요, 해당 타입이 정확히 어떤 의미인지는 인지하고 계실까요?
비슷하게 다뤄지는 타입이 많습니다. 관련한 타입의 학습은 권장드립니다.
https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement

reactelement vs reactnode 이런 키워드로 검색하면 많이 나와용

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Tab/Tab.tsx
> +      {options?.map((option) => (
[적극]
타입선언에서는 options가 반드시 있다고 나오는데, 실제 렌더링하는 쪽에서는 undefined 체크를 하고 있어요.
잘못된 부분이라 개선이 필요합니다~

2023-06-10 15:26 UTC, Jerome-Yoo commented on fe/src/components/commons/Layout/LayoutStyle.ts
> +// 전체 width
요 주석은 잘못 들어간 걸까요?

2023-06-11 10:10 UTC, Jerome-Yoo commented
- 고민거리를 다뤄보겠습니다.

> 상태 관리
> 전역으로 관리할 상태를 user정보, 메인목록에서 선택된 카테고리 필터 두 가지 정도를 생각하고 있고, 위의 두 가지 상태 외에는 해당 컴포넌트들에서 상태관리를 하려고 합니다.(차주에 구체화 할 예정)
- 좋습니다. 상태관리를 하기 위한 커뮤니케이션이 정리된 문서가 있으면 공유해주세요~
- 카테고리 필터를 전역으로 올리지 않고 범지역적인 상태로 둬도 괜찮은 설계가 나올 수 있다면, 프로바이더를 한정하는 것도 답이 될 수 있습니다.

> filter 적용시에 url에 선택된 filter를 명시적으로 추가하는 기능을 구현하여 새로고침을 해도 filter가 적용된 상태를 유지하는 방법을 고민중입니다.
- 쿼리 파라미터를 통해 달성해볼 수 있겠군요, 다만, 이렇게 되면 최초 진입시에는 쿼리파라미터가 빈값으로 들어올테니 이에 대한 엣지케이스를 다뤄주시면 될 것 같아요. 또 쿼리 파라미터를 의도적으로 수정하는 유저의 행동도 컨트롤 해야한다고 생각합니다.

2023-06-12 03:24 UTC, poco111 commented on fe/src/components/commons/Layout/LayoutStyle.ts
> +// 전체 width
네 사용하지 않는 주석으로 삭제하겠습니다!

2023-06-12 03:37 UTC, Jerome-Yoo commented
@poco111 @realsnoopso 
pnpm의 도입, 스토리북의 도입에 대해서 DM으로 나눴던 이야기를 아카이빙을 목적으로 깃헙에도 옮겨씁니다.

안녕하세요 포코, 스눕
지난주에 pnpm의 도입, 스토리북의 도입에 대해 나름대로의 견해를 작성하고 있었는데요, 업무를 시작할 때까지 글 마무리를 짓지 못해서, 러프하게 전달만 드려봅니다.
- pnpm의 도입을 고민하는 시점은 npm이나 yarn 패키지 매니저로부터의 설치 속도가 기대이하이면서 (배포될 때 문제), node_modules를 flat하게 만드는 npm3과 비교했을 때 pnpm이 충분히 가치있고, 배포레벨에서 지적되던 symlink에 대한 버그 없이 도입할 수 있는 자신감이 갖춰졌을 때. 라고 생각해요.
  - 만약 pnpm의 도입을 이력서에서 만났다면, pnpm을 도입하기 전에 패키지를 중복해서 다루는 문제 상황이 왜 발생했는지(왜 문제라고 인지했는지)를 먼저 여쭤볼 것 같아요.
  - yarn의 방식과, npm3의 방식과 어떤 차이가 있는지, pnpm을 도입하면서 생길 수 있는 허들을 인지하고 있는지를 여쭤볼 것 같아요.
    - 참고 1 : https://medium.com/pnpm/why-should-we-use-pnpm-75ca4bfe7d93
    - 참고 2: https://refine.dev/blog/pnpm-vs-npm-and-yarn/#how-does-pnpm-solve-these-problems
    - 참고 3: https://blog.siner.io/2020/12/19/npm-vs-yarn-vs-pnpm/
- 모든 컴포넌트에 대해 스토리북이 도입되느라 체력을 소모하지는 않았으면 좋겠어요. 이번 프로젝트에서 제가 전달하고 싶은 가치는, “코드스쿼드에서 마지막 프로젝트를 끝냈고, 이제 뭘 테스트하는 것이 가장 필요한지 대강 감을 잡을 수 있다” 인데요, UI는 크게 복잡하지 않은 이상 atomic한 레벨에서는 버그가 발생할 일이 적어서, 더욱이 타입스크립트를 쓰는 상황이라서 컴파일타임에 버그를 잡을 수 있다면, 스토리북을 도입하는 것과 좋은 테스트를 짜는 것이 비례하게 작업되지 않을 수 있다는 우려가 있어요.
  - 아토믹한 컴포넌트보다는 그보다 윗 레벨에서의 결합된 molecule에 상응하는 컴포넌트에 대한 테스트, 혹은 비즈니스 로직이나, 전역 상태를 다루는 영역을 테스트하는 형태가 되었으면 베스트겠다는 생각이 들어요.
  - 만약 로직테스트 말고, UI테스트에 좀 더 관심이 있다면 storybook과 chromatic을 함께 활용해보시는 것을 목표로 달려보셨으면 좋겠어요.

2023-06-12 04:49 UTC, realsnoopso commented on fe/src/assets/icons/index.ts
이 부분은 아이콘 부분입니다!
현재 아이콘을 svg로 가져오지 않고, 폰트 안의 특정 유니코드에 해당하는 문자를 아이콘으로 이용하고 있어요.
SF-Pro 폰트가 적용이 되면 저 부분이 정상적으로 보이게 됩니다.

2023-06-12 04:53 UTC, realsnoopso commented on fe/src/components/commons/Dropdown/Dropdown.tsx
> +      <Icon name={isOpen ? 'arrowUp' : 'arrowDown'}></Icon>
IDE 수준에서 레퍼런싱 기능으로 도움을 받지 못하기 때문에 ->
이 말이 정확하게 이해가 되지 않는데요..!
예를 들어 arrowRight라는 버튼이 있다고 했을때, <Icon name="arrowRight"> ... 라고 해두면 arrowRight라는 아이콘이 어디에 쓰이는지 파악하기가 어렵다, 라는 말씀이실까요?
+ 어떤 이름을 써야하는지 알기 어렵다, 라는 부분은 타입스크립트를 써두어 해당 아이콘의 키값 외에 다른 값을 쓰게 되면 에러를 뱉고, 자동완성도 해주기 때문에 문제가 되지는 않을 것이라 판단했습니다.

2023-06-12 04:54 UTC, realsnoopso commented on fe/src/components/commons/Dropdown/Dropdown.tsx
> +      <Icon name={isOpen ? 'arrowUp' : 'arrowDown'}></Icon>
그리고 저희는 color를 Icon 컴포넌트의 prop으로 받아 조정하고 있습니다..! 그래서 이름에 색상이 올 일은 없을 것 같아요!

2023-06-12 04:54 UTC, realsnoopso commented on fe/src/components/commons/Icon/Icon.tsx
> +export const Icon = ({ name = 'arrowDown', size = 16, color }: IconProps) => {
이 부분은 수정해서 반영하도록 하겠습니다 :)

2023-06-12 05:33 UTC, realsnoopso commented on fe/src/styles/index.css
> +}
말씀하신 부분은 font-display 속성을 말씀하시는걸까요?

2023-06-12 05:38 UTC, realsnoopso commented on fe/src/components/commons/Icon/Icon.tsx
> +}
그렇게 변경하도록 하겠습니다 !

2023-06-12 05:40 UTC, realsnoopso commented on fe/src/components/commons/Icon/IconStyle.ts
> +    color ? theme.colors[color] : theme.colors.neutralText};
그렇게 변경하도록 하겠습니다!

2023-06-12 05:41 UTC, poco111 commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
네네 해당 코드는 삭제하였습니다.

SEO 차원에서 apple-touch-icon(모바일 장치에서 웹사이트를 홈화면에 추가할때 사용되는 아이콘), manifest.json(유저의 데스크탑이나 모바일 디바이스 웹앱이 설치되었을 때, 아이콘, start_url 등 설정할수 있는파일)을 이용해서 웹 사이트의 검색 엔진 최적화와 사용자 경험을 향상 시킬 수 있다는 내용을 찾아보았는데, 관련해서는 조금 더 학습이 필요할 것 같습니다.

2023-06-12 05:41 UTC, realsnoopso commented on fe/src/components/commons/NavBar/NavBar.tsx
> +  onClick?: () => void;
버튼 클릭 이벤트를 optional 로 쓰면 안된다는 의견에 공감합니다. 그렇게 수정하도록 하겠습니다.

2023-06-12 05:41 UTC, realsnoopso commented on fe/src/components/commons/Profile/Profile.tsx
> +}
삭제 완료!

2023-06-12 05:44 UTC, poco111 commented on fe/package.json
> +    "lint": "eslint . --ext .js",
수정 -> "lint": "eslint . --ext .js,.ts"

타입스크립트에 대해서도 린팅 커맨트가 적용되게 수정하였습니다!

2023-06-12 05:56 UTC, realsnoopso commented on fe/src/components/commons/Profile/ProfileStyle.ts
> +    left: 50%;
넵 Editable 이라는 스타일드 컴포넌트를 하나 추가해서 역할을 명확히 해보도록 할게요!

2023-06-12 06:01 UTC, poco111 commented on fe/package.json
> +    "@storybook/testing-library": "^0.0.14-next.2",
네 npm 사이트 확인하고, 기존 버전 삭제 후에 0.1.0 버전으로 다시 설치하였습니다🫡

2023-06-12 06:13 UTC, realsnoopso commented on fe/src/components/commons/Icon/IconStyle.ts
> +    color ? theme.colors[color] : theme.colors.neutralText};
아 이 부분은 타입스크립트 때문에 이렇게 해야만 하는 상황입니다.
그러니까
1. color 와 size의 기본 값을 prop을 정의할 때부터 지정해두었음. 이렇게 하면 외부에서 color size을 지정하지 않아도 됨
<img width="1053" alt="Screenshot 2023-06-12 at 3 12 26 PM" src="https://github.com/codesquad-members-2023/second-hand/assets/96381221/978b01e9-fa68-420c-9d36-38392fa2d6c7">
2. 그러나 이렇게 되면 이런 타입 에러가 발생합니다. 그래서 이곳에서도 기본 값을 지정해두긴 해야 하는 상황입니다.

2023-06-12 06:19 UTC, realsnoopso commented on fe/src/components/commons/Tab/Tab.tsx
> +      {options?.map((option) => (
수정하도록 하겠습니다~!

2023-06-12 06:20 UTC, realsnoopso commented on fe/src/components/commons/Tab/Tab.tsx
> +  children: ReactElement | string;
이 부분은 학습을 제대로 못하고 지나친것 같습니다..!

ReactElement가 ReactNode에 포함되는 개념이었군요. 이 경우에는 ReactNode로 작성하는게 더 적절할 것 같습니다.

2023-06-12 06:43 UTC, poco111 commented on fe/package.json
> +    "styled-components": "6.0.0-rc.3",
네 설치 과정에서 문제가 발생하지는 않았지만, 버전 6 설치 과정에서 이슈 발생 가능성을 확인하였고, 안정화된 버전으로 재설치 하였습니다.
styled-component version 6 설치 오류 관련 내용 : https://github.com/styled-components/styled-components/issues/3998

2023-06-12 06:46 UTC, poco111 commented on fe/src/styles/GlobalStyle.ts
"스타일을 리셋하는 것을 보수적으로 접근하는 편입니다." 이 부분과 관련해서 빰빰의 생각이 궁금합니다
보수적으로 접근해야하는 이유가 무엇일까요?

아래에 보내주신 링크들은 참고해서 읽어보겠습니다!

2023-06-12 06:56 UTC, poco111 commented on fe/src/reportWebVitals.ts
네네 웹 퍼포먼스에 대해서는 인지를 하게 되었고, 코멘트 주신 사이트와 유튜브도 참고하도록 하겠습니다! 
그리고 웹 퍼포먼스 관련해서는 스눕과 상의해본 결과, 어느정도 개발이 진행된 이후에 함께 고려해보는 것으로 결정했는데, 혹시 향후에 어드바이스가 필요할 때 빰빰에게 질문드려도 될까요? 🧐

2023-06-12 06:58 UTC, poco111 commented on fe/src/styles/Typography.ts
🙇🙇‍♀️

2023-06-12 06:58 UTC, poco111 commented on fe/src/components/commons/Button/ButtonStyle.ts
🙇🙇‍♀️

2023-06-12 07:44 UTC, Jerome-Yoo commented on fe/src/components/commons/Dropdown/Dropdown.tsx
> +      <Icon name={isOpen ? 'arrowUp' : 'arrowDown'}></Icon>
1. 아 네네 arrowRight 아이콘의 사용여부를 트래킹하기 어렵다는 문제를 의미한 것이었습니다. name으로 svg를 픽해오는 방식 말고 컴포넌트로서 각각을 선언하면 cmd+클릭 으로 어디서 쓰였는지를 트래킹할 수 있다는 의미였습니다.

2-3의 답변을 보니 1의 문제 발생 가능성과는 별개로 관리가 될 수 있을 것 같다는 생각이 듭니다. 👍

2023-06-12 07:45 UTC, Jerome-Yoo commented on fe/src/reportWebVitals.ts
좋습니다. 경험상 아마도 개발 끝나는 시점까지 퍼포먼스로 고생할일은 없을 것 같기도 해요!
그치만 줌밋은 언제든지 환영입니다!

2023-06-12 07:51 UTC, Jerome-Yoo commented on fe/src/styles/GlobalStyle.ts
저는 사회적 약자를 위한 프로젝트에 관심이 많은 편이에요.

몇년전에 프로젝트를 위해 시각장애인분들을 인터뷰해보면서 느꼈던 것인데, 시맨틱하지 않은 웹을 탐색하는것에 아주 큰 고통을 갖고 계시더라구요. 핸디캡을 가진 분들이 사용하는 브라우징하는데에 도움을 주는 도구들이 웹 접근성을 가이드라인 삼아 개발되었어서 개인적으로는 FE로서 접근성을 가급적 지키기 위해 학습을 해오고 있어요. 

그런 맥락에서 브라우저가 기본적으로 제공한 스타일을 변경하는 것(예를 들면 기본 폰트 크기의 강제적인 downsizing, 색상대비 조정 등)을 조심해야한다는 의미였습니다.

2023-06-12 07:52 UTC, Jerome-Yoo commented on fe/src/styles/index.css
> +}
아 src에 일단 넣게되면 index.css를 불러온 시점에 ttf파일을 내려받겠죠?
그러면 아마 ttf파일 다운로드가 끝날 때까지 다른 파일들이 블락될 가능성이 있어서 제안을 드려봤습니다.
이 문서가 도움이 될 수도 있겠어요 https://web.dev/i18n/ko/optimize-webfont-loading/

2023-06-12 07:58 UTC, Jerome-Yoo commented on fe/src/components/commons/Icon/IconStyle.ts
> +    color ? theme.colors[color] : theme.colors.neutralText};
`import { css } from 'styled-components'`
```suggestion
${({ theme, color }) => color && css`color: theme.colors[color]`;}
```
IDE에서 체크해보지는 않았는데 요러면 되지 않을까요?

2023-06-12 08:22 UTC, Jerome-Yoo approved these changes
LGTM 👍 
고생하셨습니다!!

참고차원에서의 코멘트
- fe/src/assets/icons/index.ts의 이모지는 SF-Pro 폰트의 사용을 반드시 필요로 하는데요, 어떤 이유로인해 폰트파일이 다운로드가 안되거나 적용이 안되거나 하는 경우가 있을 수 있습니다. fallback하는 경우를 평가해서 대처할 수 잇도록 하는게 좋아보여요.
- 주석은 가급적 포맷팅이 있는게 트래킹되기 쉽습니다. '//'만으로 검색하면 눈에 안보이는게 훨씬 많거든요
- 컴포넌트 디렉토리 하위의 styled컴포넌트만을 다룬 파일은 styles.ts 가 되어도 괜찮아보여요. 한번 선언하고 나면 더이상 활용하지 않거든요. 어짜피 뽑아 쓸때로 S라는 이름으로 뭉개기도 하구요
- 마찬가지로 컴포넌트 파일의 이름이 index.tsx가 되어도 괜찮아요. 선언해서 쓸 때, IDE에서 열때 결국 어떤 파일을 보고 있는지 알 수 있거든요.

2023-06-12 08:33 UTC, merged